<!--  included footer -->
<div id="footer" class="container_12">
  <div id="nav_secondary" class="grid_8 alpha">
    <ul class="navigation">
      <li><a href="/pages/home">Home</a></li>
      <li class="separator">|</li>
      <li><a href="/pages/about">About Us</a></li>
      <li class="separator">|</li>
      <li><a href="/pages/privacy">Privacy &amp; Terms</a></li>
    </ul>
  </div>
  <div class="grid_4 omega"></div>
</div>
<div id="copyright" class="container_12 center">&copy;2011 All rights reserved</div>
