<!--  included footer -->
<div id="footer" class="container_12">
  <div id="copyright" class="grid_5 alpha">&copy;2011 All rights reserved</div>
  <div id="nav_secondary" class="grid_7 omega">
    <ul class="navigation">
      <li><a href="/pages/terms">Terms and Conditions</a></li>
      <li class="separator">|</li>
      <li><a href="/pages/privacy">Privacy Policy</a></li>
      <li class="separator">|</li>
      <li><a href="/pages/contact">Contact Us</a></li>
      <li class="separator">|</li>
      <li><a href="/pages/about">About Us</a></li>
      <li class="separator">|</li>
      <li><a href="/pages/home">Home</a></li>
    </ul>
  </div>
</div>