<!-- included header -->
<div id="header" class="container_12">
  <div class="grid_9 alpha">
    <h1 id="logo">LocationMonitor.com</h1>
    <div id="nav_primary">
      <ul class="navigation">
        <li id="services"><a href="/pages/features">Features</a></li>
        <li class="separator">|</li>
        <li id="list"><a href="/user/signup">Monitor your business</a></li>
        <li class="separator">|</li>
        <li id="partner"><a href="/pages/partner">Partner programs</a></li>
        <li class="separator">|</li>
        <li id="faq"><a href="/pages/faq">FAQs</a></li>
      </ul>
    </div>
  </div>
  <div id="registration" class="grid_3 omega">
    <ul class="navigation">
      <li id="login"><a href="https://www.locationmonitor.com/user/login"><img src="/assets/images/btn-login.png"/></a></li>
      <li id="sign_up"><a href="https://www.locationmonitor.com/user/signup"><img src="/assets/images/btn-sign-up.png"/></a></li>
    </ul>
  </div>
</div>