<!--  included footer -->
<div id="footer" class="container_12">
  <div id="copyright" class="grid_5 alpha">&copy;2011 All rights reserved</div>
  <div id="nav_secondary" class="grid_7 omega">
    <ul class="navigation">
      <li><a href="#">Terms and Conditions</a></li>
      <li class="separator">|</li>
      <li><a href="#">Privacy Policy</a></li>
      <li class="separator">|</li>
      <li><a href="#">Contact Us</a></li>
      <li class="separator">|</li>
      <li><a href="#">About Us</a></li>
      <li class="separator">|</li>
      <li><a href="#">Home</a></li>
    </ul>
  </div>
</div>