<!--  included footer -->
<div id="footer" class="container_12">
  <div id="copyright" class="grid_5 alpha">&copy;2011 All rights reserved</div>
  <div id="nav_secondary" class="grid_7 omega">
    <ul class="navigation">
      <li><a href="terms.php">Terms and Conditions</a></li>
      <li class="separator">|</li>
      <li><a href="privacy.php">Privacy Policy</a></li>
      <li class="separator">|</li>
      <li><a href="contact.php">Contact Us</a></li>
      <li class="separator">|</li>
      <li><a href="about.php">About Us</a></li>
      <li class="separator">|</li>
      <li><a href="index.php">Home</a></li>
    </ul>
  </div>
</div>