<!-- included header -->
<div id="header" class="container_12">
  <div class="grid_9 alpha">
    <h1 id="logo">LocationMonitor.com</h1>
    <div id="nav_primary">
      <ul class="navigation">
        <li id="services"><a href="#">Services</a></li>
        <li class="separator">|</li>
        <li id="list"><a href="#">List your business</a></li>
        <li class="separator">|</li>
        <li id="partner"><a href="#">Partner programs</a></li>
        <li class="separator">|</li>
        <li id="faq"><a href="#">FAQs</a></li>
      </ul>
    </div>
  </div>
  <div id="registration" class="grid_3 omega">
    <ul class="navigation">
      <li id="login"><a href="#"><img src="images/btn-login.png"/></a></li>
      <li id="sign_up"><a href="#"><img src="images/btn-sign-up.png"/></a></li>
    </ul>
  </div>
</div>